name: Javascript Action
description: A JavaScript action that opens an issue
author: Olha Polishchuk

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  token:
    description: "GitHub token"
    required: true
  title:
    description: "Issue title"
    required: true
  body:
    description: "Issue body"
  assignees:
    description: "Assignees"

# Define your outputs here.
outputs:
  issue:
    description: "The issue object as a json string"

runs:
  using: node20
  main: dist/index.js
